name: 'Json Fields'
description: 'Create JSON file with filtered fields (unique/duplicate)'
author: 'AlexRogalskiy'

inputs:
  jsonMode:
    description: 'JSON operation mode (unique/duplicate)'
    required: true
  sourceFile:
    description: 'JSON source file'
    required: true
  targetPath:
    description: 'Target path to store filtered JSON file'
    required: true
  destFile:
    description: 'JSON destination file name'
    required: true
  targetProperty:
    description: 'JSON target property name to operate by'
    required: true
  fields:
    description: 'JSON fields to operate by'
    required: true

outputs:
  status:
    description: 'JSON operation status'

runs:
  using: 'node12'
  main: 'dist/index.js'

# Ref: https://haya14busa.github.io/github-action-brandings/
branding:
  icon: 'file-text'
  color: 'white'
