#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npm run lint:staged
npm run all
npm run test:all
npm run changelog

git add docs/
git add src/
git add tests/
git add typings/

git add -f dist/action.js
git add -f dist/esprima.js
git add -f dist/index.js
git add -f dist/module.js

git add README.md
git add CHANGELOG.md
git add package-lock.json
